### ISSUE TITLE
url scheme "localsend://" or "ls://"

### ISSUE THREAD

**Issue by vincivermeer** [localsend/protocol#9]
Hi everyone.

I would like to know if you all have already thought about registering a custom url for the localsend protocol. Have you all ever thought of registering a custom url for the localsend protocol?

For example: `localsend://` or `ls://`?

why?
- This allows you to create custom links. For example, the proposed url scheme would look like this:  `localsend://<device>:<file>`

**Comment by Tienisto** [comment]
Hi,

I don't think that it will be useful.
If you want to get a file via link, then you can wait for https://github.com/localsend/localsend/issues/198 being implemented.
Then you can just type `http://<ip>:<port>` and then you can select the file to download.

**Comment by Tienisto** [comment]
Alright, thanks for your feedback!

**Comment by derhuerst** [comment]
I think having a `localsend://` URL scheme would be very useful.

If, one day, hopefully, localsend supports sending files completely peer-to-peer over ad-hoc networking (like AirDrop), if the app offers a QR code to facilitate the discovery & key exchange between the devices, why not make it a proper URL, so that the app is opened when scanning the QR code?
